"""
Ansible integration activities.

Two responsibilities live here:
  1. render_config — convert a DeviceIntent into a concrete IOS-XE
     configuration file via Jinja2.
  2. push_config  — hand that file to Ansible for delivery to the device.

Keeping rendering and pushing as separate activities matters for two reasons:
  - The rendered config is an immutable artifact stored in workflow history.
    If a push retry fires, it pushes the same bytes — not a re-render that
    might silently pick up a mid-flight Nautobot change.
  - Temporal can checkpoint between them, so a crash after render but before
    push doesn't require re-rendering.
"""

from __future__ import annotations

import asyncio
import logging
import textwrap
from datetime import UTC, datetime

from jinja2 import BaseLoader, Environment, StrictUndefined
from temporalio import activity

from temporal.models import DeviceIntent, PushResult, RenderedConfig

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# IOS-XE configuration template
#
# Written as a module-level constant so the Jinja2 environment is built once
# at import time rather than on every activity invocation.
#
# Template conventions:
#   - `strict` undefined mode: a missing variable surfaces immediately as a
#     Jinja2 UndefinedError rather than silently rendering an empty string
#     into the config — which could produce a valid-but-wrong device config.
#   - All blocks use explicit `{%- -%}` whitespace control so the rendered
#     output is clean enough to review as a diff.
# ---------------------------------------------------------------------------
_IOS_XE_TEMPLATE = textwrap.dedent("""\
    ! ============================================================
    ! Hostname & identity
    ! Generated by network-ztp — do not edit manually
    ! ============================================================
    hostname {{ intent.hostname }}
    !
    ip domain-name corp.example.com
    ip name-server 8.8.8.8
    !
    ! ============================================================
    ! Clock / NTP
    ! ============================================================
    clock timezone UTC 0 0
    {%- for ntp in intent.ntp_servers %}
    ntp server {{ ntp }}
    {%- endfor %}
    !
    ! ============================================================
    ! Logging
    ! ============================================================
    logging on
    logging buffered 16384
    {%- for syslog in intent.syslog_servers %}
    logging host {{ syslog }}
    {%- endfor %}
    logging trap informational
    !
    ! ============================================================
    ! VLANs
    ! ============================================================
    {%- for vlan in intent.vlans %}
    vlan {{ vlan.vlan_id }}
     name {{ vlan.name }}
    {%- endfor %}
    !
    ! ============================================================
    ! Interfaces
    ! ============================================================
    {%- for iface in intent.interfaces %}
    interface {{ iface.name }}
    {%- if iface.description %}
     description {{ iface.description }}
    {%- endif %}
    {%- if iface.ip_address %}
     ip address {{ iface.ip_address | ip_to_ios }}
    {%- endif %}
    {%- if iface.enabled %}
     no shutdown
    {%- else %}
     shutdown
    {%- endif %}
    !
    {%- endfor %}
    !
    ! ============================================================
    ! BGP (eBGP stub toward hub)
    ! ============================================================
    router bgp {{ intent.bgp_asn }}
     bgp router-id {{ intent.primary_ip | cidr_to_host }}
     bgp log-neighbor-changes
    {%- if intent.bgp_peer_ip %}
     neighbor {{ intent.bgp_peer_ip }} remote-as {{ intent.bgp_peer_asn }}
     neighbor {{ intent.bgp_peer_ip }} description MPLS-HUB
     neighbor {{ intent.bgp_peer_ip }} soft-reconfiguration inbound
     !
     address-family ipv4
      neighbor {{ intent.bgp_peer_ip }} activate
      network {{ intent.primary_ip | cidr_to_network }} mask {{ intent.primary_ip | cidr_to_mask }}
     exit-address-family
    {%- endif %}
    !
    ! ============================================================
    ! SSH / AAA baseline
    ! ============================================================
    aaa new-model
    aaa authentication login default local
    aaa authorization exec default local
    !
    ip ssh version 2
    ip ssh time-out 60
    ip ssh authentication-retries 3
    !
    line vty 0 15
     transport input ssh
     login authentication default
    !
    end
""")


def _ip_to_ios(cidr: str) -> str:
    """Convert '10.1.1.1/30' to '10.1.1.1 255.255.255.252' for IOS syntax."""
    if not cidr or "/" not in cidr:
        return cidr
    host, prefix = cidr.split("/")
    bits = int(prefix)
    mask_int = (0xFFFFFFFF << (32 - bits)) & 0xFFFFFFFF
    mask = ".".join(str((mask_int >> shift) & 0xFF) for shift in (24, 16, 8, 0))
    return f"{host} {mask}"


def _cidr_to_host(cidr: str) -> str:
    """Extract host address from CIDR notation."""
    return cidr.split("/")[0] if "/" in cidr else cidr


def _cidr_to_network(cidr: str) -> str:
    """Return the network address for a host CIDR (assumes /32 loopback style)."""
    return cidr.split("/")[0] if "/" in cidr else cidr


def _cidr_to_mask(cidr: str) -> str:
    """Return the dotted-decimal subnet mask from a CIDR prefix length."""
    prefix = int(cidr.split("/")[1]) if "/" in cidr else 32
    mask_int = (0xFFFFFFFF << (32 - prefix)) & 0xFFFFFFFF
    return ".".join(str((mask_int >> shift) & 0xFF) for shift in (24, 16, 8, 0))


def _build_jinja_env() -> Environment:
    env = Environment(loader=BaseLoader(), undefined=StrictUndefined, keep_trailing_newline=True)
    env.filters["ip_to_ios"] = _ip_to_ios
    env.filters["cidr_to_host"] = _cidr_to_host
    env.filters["cidr_to_network"] = _cidr_to_network
    env.filters["cidr_to_mask"] = _cidr_to_mask
    return env


_JINJA_ENV = _build_jinja_env()


@activity.defn
async def render_config(intent: DeviceIntent) -> RenderedConfig:
    """
    Render a Jinja2 IOS-XE configuration from a DeviceIntent.

    The rendered output is stored as an immutable workflow artifact so that
    push retries are idempotent: they always push the same config bytes that
    were validated at render time, regardless of any Nautobot changes that
    might occur between render and push.

    Args:
        intent: Fully-populated desired state from Nautobot.

    Returns:
        RenderedConfig containing the complete IOS-XE config text.

    Raises:
        jinja2.UndefinedError: If the template references a field missing from intent.
    """
    activity.logger.info(
        "Rendering IOS-XE config for device_id=%s hostname=%s",
        intent.device_id,
        intent.hostname,
    )

    template = _JINJA_ENV.from_string(_IOS_XE_TEMPLATE)
    config_text = template.render(intent=intent)

    line_count = config_text.count("\n")
    activity.logger.info(
        "Config rendered successfully: device_id=%s lines=%d",
        intent.device_id,
        line_count,
    )

    return RenderedConfig(
        device_id=intent.device_id,
        config_content=config_text,
        template_name="ios_xe_branch_router.j2",
        rendered_at=datetime.now(tz=UTC),
    )


@activity.defn
async def push_config(config: RenderedConfig) -> PushResult:
    """
    Push a rendered configuration to the target device via Ansible.

    In production this activity spawns ``ansible-runner`` as a subprocess,
    passing the rendered config as an extra var. The 2-second sleep below
    simulates realistic push latency (~10-60s in production depending on
    device reachability and config size).

    The Ansible inventory is expected to contain the device under its
    ``device_id`` as the host key, with ``ansible_host`` set to the
    management IP and credentials sourced from Ansible Vault.

    Args:
        config: Rendered device configuration to push.

    Returns:
        PushResult with Ansible stdout/stderr and timing information.
    """
    start = asyncio.get_event_loop().time()

    ansible_cmd = [
        "ansible-runner",
        "run",
        "/opt/ansible/projects/ztp",
        "--playbook",
        "push_config.yml",
        "--inventory",
        "/opt/ansible/inventory",
        "--extravars",
        f"target_device={config.device_id}",
        "--extravars",
        f"config_rendered_at={config.rendered_at.isoformat()}",
    ]

    activity.logger.info(
        "[MOCK] Would execute: %s",
        " ".join(ansible_cmd),
    )
    activity.logger.info(
        "Pushing config for device_id=%s (%d bytes)",
        config.device_id,
        len(config.config_content),
    )

    # Simulate the network round-trip and Ansible task execution.
    await asyncio.sleep(2)

    duration = asyncio.get_event_loop().time() - start

    mock_output = (
        f"PLAY [Push branch router config] **************************************\n"
        f"\n"
        f"TASK [Gather facts] ***************************************************\n"
        f"ok: [{config.device_id}]\n"
        f"\n"
        f"TASK [Deploy IOS-XE configuration] ************************************\n"
        f"changed: [{config.device_id}] => (config lines pushed: "
        f"{config.config_content.count(chr(10))})\n"
        f"\n"
        f"PLAY RECAP ************************************************************\n"
        f"{config.device_id}  : ok=2  changed=1  unreachable=0  failed=0\n"
    )

    activity.logger.info(
        "Config push complete: device_id=%s duration=%.2fs",
        config.device_id,
        duration,
    )

    return PushResult(
        device_id=config.device_id,
        success=True,
        output=mock_output,
        duration_seconds=round(duration, 3),
    )
