"""
Ansible integration activities.

Two responsibilities:
  1. render_config — convert a DeviceIntent into a concrete IOS-XE configuration
     via Jinja2.  StrictUndefined ensures a missing template variable raises
     immediately rather than silently producing an empty-string field in the
     device config.

  2. push_config — hand the rendered config to ansible-runner for SSH delivery.
     In production, ansible_runner.run() spawns the Ansible process and streams
     its stdout/stderr back as structured events.  The activity wraps it in
     asyncio.to_thread() because ansible-runner is synchronous.

Why render and push are separate activities:
    The RenderedConfig object is stored in Temporal workflow history as an
    immutable artifact.  If the push activity fails and retries, it always
    pushes the same bytes — not a re-render that might silently pick up a
    mid-flight Nautobot change.  A crash between render and push does not
    require re-rendering.
"""

from __future__ import annotations

import asyncio
import textwrap
from datetime import UTC, datetime

import ansible_runner
import structlog
from jinja2 import BaseLoader, Environment, StrictUndefined
from temporalio import activity

from temporal.models import DeviceIntent, PushResult, RenderedConfig

log = structlog.get_logger()

# ---------------------------------------------------------------------------
# IOS-XE configuration template
#
# Module-level constant so the Jinja2 environment is built once at import time.
#
# Conventions:
#   - StrictUndefined: missing variable → immediate UndefinedError, not silent ""
#   - {%- -%} whitespace control keeps diffs readable
#   - Jinja2 filters handle IOS address notation (see _build_jinja_env)
# ---------------------------------------------------------------------------
_IOS_XE_TEMPLATE = textwrap.dedent("""\
    ! ============================================================
    ! Generated by network-ztp — do not edit manually
    ! Device : {{ intent.hostname }}
    ! Rendered: {{ rendered_at }}
    ! ============================================================
    !
    hostname {{ intent.hostname }}
    !
    ip domain-name corp.example.com
    ip name-server 8.8.8.8
    no ip domain-lookup
    !
    ! ── NTP ──────────────────────────────────────────────────────
    clock timezone UTC 0 0
    {%- for ntp in intent.ntp_servers %}
    ntp server {{ ntp }}
    {%- endfor %}
    !
    ! ── Syslog ───────────────────────────────────────────────────
    logging on
    logging buffered 16384
    logging console critical
    {%- for syslog in intent.syslog_servers %}
    logging host {{ syslog }}
    {%- endfor %}
    logging trap informational
    !
    ! ── VLANs ────────────────────────────────────────────────────
    {%- for vlan in intent.vlans %}
    vlan {{ vlan.vlan_id }}
     name {{ vlan.name }}
    {%- endfor %}
    !
    ! ── Interfaces ───────────────────────────────────────────────
    {%- for iface in intent.interfaces %}
    interface {{ iface.name }}
    {%- if iface.description %}
     description {{ iface.description }}
    {%- endif %}
    {%- if iface.ip_address %}
     ip address {{ iface.ip_address | ip_to_ios }}
    {%- endif %}
    {%- if not iface.enabled %}
     shutdown
    {%- else %}
     no shutdown
    {%- endif %}
    !
    {%- endfor %}
    !
    ! ── BGP eBGP stub toward hub ─────────────────────────────────
    router bgp {{ intent.bgp_asn }}
     bgp router-id {{ intent.primary_ip | cidr_to_host }}
     bgp log-neighbor-changes
    {%- if intent.bgp_peer_ip %}
     neighbor {{ intent.bgp_peer_ip }} remote-as {{ intent.bgp_peer_asn }}
     neighbor {{ intent.bgp_peer_ip }} description MPLS-HUB
     neighbor {{ intent.bgp_peer_ip }} soft-reconfiguration inbound
     neighbor {{ intent.bgp_peer_ip }} send-community
     !
     address-family ipv4
      neighbor {{ intent.bgp_peer_ip }} activate
      network {{ intent.primary_ip | cidr_to_network }} mask {{ intent.primary_ip | cidr_to_mask }}
     exit-address-family
    {%- endif %}
    !
    ! ── SNMP v2c read-only ────────────────────────────────────────
    snmp-server community public RO
    snmp-server location {{ intent.hostname }}
    snmp-server contact noc@corp.example.com
    snmp-server enable traps
    !
    ! ── SSH / AAA baseline ───────────────────────────────────────
    aaa new-model
    aaa authentication login default local
    aaa authorization exec default local
    !
    ip ssh version 2
    ip ssh time-out 60
    ip ssh authentication-retries 3
    ip ssh source-interface {{ intent.mgmt_interface }}
    !
    line vty 0 15
     transport input ssh
     login authentication default
     exec-timeout 15 0
    !
    ! ── Housekeeping ─────────────────────────────────────────────
    no service pad
    service timestamps debug datetime msec localtime show-timezone
    service timestamps log datetime msec localtime show-timezone
    service password-encryption
    !
    end
""")


def _ip_to_ios(cidr: str) -> str:
    """'10.1.1.1/30' → '10.1.1.1 255.255.255.252' for IOS 'ip address' syntax."""
    if not cidr or "/" not in cidr:
        return cidr
    host, prefix = cidr.split("/")
    bits = int(prefix)
    mask_int = (0xFFFFFFFF << (32 - bits)) & 0xFFFFFFFF
    mask = ".".join(str((mask_int >> shift) & 0xFF) for shift in (24, 16, 8, 0))
    return f"{host} {mask}"


def _cidr_to_host(cidr: str) -> str:
    return cidr.split("/")[0] if "/" in cidr else cidr


def _cidr_to_network(cidr: str) -> str:
    return cidr.split("/")[0] if "/" in cidr else cidr


def _cidr_to_mask(cidr: str) -> str:
    prefix = int(cidr.split("/")[1]) if "/" in cidr else 32
    mask_int = (0xFFFFFFFF << (32 - prefix)) & 0xFFFFFFFF
    return ".".join(str((mask_int >> shift) & 0xFF) for shift in (24, 16, 8, 0))


def _build_jinja_env() -> Environment:
    env = Environment(loader=BaseLoader(), undefined=StrictUndefined, keep_trailing_newline=True)
    env.filters["ip_to_ios"] = _ip_to_ios
    env.filters["cidr_to_host"] = _cidr_to_host
    env.filters["cidr_to_network"] = _cidr_to_network
    env.filters["cidr_to_mask"] = _cidr_to_mask
    return env


_JINJA_ENV = _build_jinja_env()


@activity.defn
async def render_config(intent: DeviceIntent) -> RenderedConfig:
    """
    Render a Jinja2 IOS-XE configuration from a DeviceIntent.

    The rendered text is stored as an immutable workflow artifact — push retries
    always push the same bytes, regardless of Nautobot changes after render time.
    """
    log.info("render_config.started", device_id=intent.device_id, hostname=intent.hostname)

    rendered_at = datetime.now(tz=UTC).isoformat()
    template = _JINJA_ENV.from_string(_IOS_XE_TEMPLATE)
    config_text = template.render(intent=intent, rendered_at=rendered_at)

    log.info(
        "render_config.complete",
        device_id=intent.device_id,
        lines=config_text.count("\n"),
        bytes=len(config_text),
    )

    return RenderedConfig(
        device_id=intent.device_id,
        config_content=config_text,
        template_name="ios_xe_branch_router.j2",
        rendered_at=datetime.now(tz=UTC),
    )


@activity.defn
async def push_config(config: RenderedConfig) -> PushResult:
    """
    Push a rendered configuration to the target device via Ansible.

    Production path: ansible_runner.run() spawns the Ansible process synchronously,
    streaming structured events.  Wrapped in asyncio.to_thread() so it does not
    block the Temporal activity event loop.

    The Ansible project at /opt/ansible/projects/ztp is expected to contain:
      - push_config.yml: playbook that applies config_content to target_device
      - inventory/: static or dynamic inventory with device credentials from Vault
    """
    log.info(
        "push_config.started",
        device_id=config.device_id,
        config_bytes=len(config.config_content),
        rendered_at=config.rendered_at.isoformat(),
    )

    extravars = {
        "target_device": config.device_id,
        "config_content": config.config_content,
        "config_rendered_at": config.rendered_at.isoformat(),
    }

    # In production: remove the USE_MOCK guard and this runs for real.
    # ansible_runner.run() is synchronous; to_thread keeps the event loop free.
    USE_MOCK = True  # noqa: N806

    if not USE_MOCK:
        result = await asyncio.to_thread(
            ansible_runner.run,
            project_dir="/opt/ansible/projects/ztp",
            playbook="push_config.yml",
            inventory="/opt/ansible/inventory",
            extravars=extravars,
            quiet=False,
        )
        success = result.rc == 0
        output = "\n".join(str(e) for e in result.events)
    else:
        log.debug(
            "push_config.mock",
            ansible_cmd="ansible-runner run /opt/ansible/projects/ztp --playbook push_config.yml",
            extravars=extravars,
        )
        await asyncio.sleep(2)  # simulate network round-trip + Ansible task execution
        success = True
        output = (
            f"PLAY [Push router config] ************************************\n"
            f"TASK [Gather facts] ******************************************\n"
            f"ok: [{config.device_id}]\n"
            f"TASK [Deploy IOS-XE configuration] **************************\n"
            f"changed: [{config.device_id}] => "
            f"(config lines: {config.config_content.count(chr(10))})\n"
            f"PLAY RECAP ***************************************************\n"
            f"{config.device_id}  : ok=2  changed=1  unreachable=0  failed=0\n"
        )

    log.info("push_config.complete", device_id=config.device_id, success=success)

    return PushResult(
        device_id=config.device_id,
        success=success,
        output=output,
        duration_seconds=2.0,
    )
