"""
Day 0 bootstrap activities.

Sequence:
  1. register_dhcp_reservation  — pre-create a MAC reservation so the device's
                                   first DHCP Discover gets the right IP + Option 67.
  2. render_bootstrap_script    — Jinja2-render a minimal IOS-XE ZTP Python script.
  3. publish_bootstrap_script   — write the script to the HTTP file server directory.
  4. wait_for_device_reachability — poll SSH port 22 until the device checks in.

Bootstrap flow on the device side (Cisco IOS-XE ZTP):
  1. Device boots with factory defaults (no config).
  2. Sends DHCP Discover on all interfaces.
  3. DHCP returns reserved IP + Option 67 URL.
  4. IOS-XE fetches the Python script from the URL.
  5. IOS-XE executes it via its built-in Python + ``cli`` module.
  6. Script applies minimal config: hostname, mgmt IP, default route, SSH.
  7. Device saves and becomes reachable → Day 1 begins.

Reachability polling uses tenacity for fine-grained control over the retry
interval and jitter. The Temporal activity-level timeout (8 hours, set in the
workflow) is the outer bound; tenacity manages the inner polling cadence.
"""

from __future__ import annotations

import asyncio
import os
import textwrap
from datetime import UTC, datetime

import structlog
from jinja2 import BaseLoader, Environment, StrictUndefined
from opentelemetry import trace as _otel_trace
from temporalio import activity
from tenacity import retry, stop_after_delay, wait_fixed

from temporal.models import BootstrapScript, DeviceIntent, DhcpReservation

log = structlog.get_logger()
_tracer = _otel_trace.get_tracer(__name__)

BOOTSTRAP_SERVER_URL = os.getenv("BOOTSTRAP_SERVER_URL", "http://bootstrap.corp.example.com")
BOOTSTRAP_SERVE_DIR = os.getenv("BOOTSTRAP_SERVE_DIR", "/opt/bootstrap/scripts")
DHCP_API_URL = os.getenv("DHCP_API_URL", "http://localhost:8081")

# Flip to False (or set ZTP_USE_MOCK=false) to call real APIs.
_USE_MOCK: bool = os.getenv("ZTP_USE_MOCK", "true").lower() != "false"

# ---------------------------------------------------------------------------
# IOS-XE ZTP Python script template
#
# Executed on the device by its built-in Python 3 + ``cli`` module on first
# boot.  Only the ``cli`` module is available — no pip, no stdlib networking.
# ---------------------------------------------------------------------------
_ZTP_SCRIPT_TEMPLATE = textwrap.dedent("""\
    #!/usr/bin/env python3
    \"\"\"
    IOS-XE ZTP bootstrap script for {{ intent.hostname }}.
    Auto-generated by network-ztp — do not edit manually.
    Rendered: {{ rendered_at }}
    \"\"\"
    import cli
    import time

    HOSTNAME = "{{ intent.hostname }}"
    MGMT_IFACE = "{{ intent.mgmt_interface }}"
    MGMT_IP = "{{ intent.primary_ip | ip_to_ios }}"
    DEFAULT_GW = "{{ intent.default_gateway }}"
    DOMAIN_NAME = "corp.example.com"

    def configure_management() -> None:
        \"\"\"Apply minimal management-plane configuration.\"\"\"
        cli.configure([
            f"hostname {HOSTNAME}",
            f"interface {MGMT_IFACE}",
            f" description ZTP-MGMT",
            f" ip address {MGMT_IP}",
            f" no shutdown",
            f"ip route 0.0.0.0 0.0.0.0 {DEFAULT_GW}",
            f"ip domain-name {DOMAIN_NAME}",
        ])

    def configure_ssh() -> None:
        \"\"\"Enable SSH for Day 1 Ansible connection.\"\"\"
        cli.execute("crypto key generate rsa modulus 2048")
        time.sleep(2)
        cli.configure([
            "ip ssh version 2",
            "ip ssh time-out 60",
            "ip ssh authentication-retries 3",
            "aaa new-model",
            "aaa authentication login default local",
            "aaa authorization exec default local",
            "line vty 0 15",
            " login authentication default",
            " transport input ssh",
        ])

    def save_config() -> None:
        cli.execute("write memory")

    configure_management()
    configure_ssh()
    save_config()
    print(f"ZTP bootstrap complete for {HOSTNAME}")
""")

_JINJA_ENV = Environment(loader=BaseLoader(), undefined=StrictUndefined, keep_trailing_newline=True)


def _ip_to_ios(cidr: str) -> str:
    """'10.1.1.1/30' → '10.1.1.1 255.255.255.252'"""
    if not cidr or "/" not in cidr:
        return cidr
    host, prefix = cidr.split("/")
    bits = int(prefix)
    mask_int = (0xFFFFFFFF << (32 - bits)) & 0xFFFFFFFF
    mask = ".".join(str((mask_int >> shift) & 0xFF) for shift in (24, 16, 8, 0))
    return f"{host} {mask}"


_JINJA_ENV.filters["ip_to_ios"] = _ip_to_ios


@activity.defn
async def register_dhcp_reservation(
    mac_address: str, device_id: str, hostname: str
) -> DhcpReservation:
    """
    Pre-create a DHCP host reservation keyed on MAC address.

    The reservation sets:
      - fixed-address: the management IP from Nautobot
      - option bootfile-name (67): the per-device ZTP script URL
      - lease time: 1 hour (enough for bootstrap; prevents long-term pool squatting)

    In production this POSTs to the DHCP server's management API
    (ISC DHCP, Kea, or Infoblox REST).
    """
    with _tracer.start_as_current_span("register_dhcp_reservation") as span:
        span.set_attribute("device.id", device_id)
        script_url = f"{BOOTSTRAP_SERVER_URL}/ztp/{device_id}.py"
        dhcp_payload = {
            "mac": mac_address,
            "hostname": hostname,
            "option67": script_url,
            "lease_time": 3600,
        }

        log.info(
            "register_dhcp_reservation.started",
            mac_address=mac_address,
            device_id=device_id,
            script_url=script_url,
        )

        if _USE_MOCK:
            log.debug(
                "register_dhcp_reservation.mock",
                dhcp_api=f"{DHCP_API_URL}/api/reservations",
                payload=dhcp_payload,
            )
        else:
            import httpx

            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.post(
                    f"{DHCP_API_URL}/api/reservations",
                    json=dhcp_payload,
                )
                response.raise_for_status()

        log.info("register_dhcp_reservation.complete", device_id=device_id, mac_address=mac_address)
        return DhcpReservation(
            device_id=device_id,
            mac_address=mac_address,
            assigned_ip="10.100.255.1",
            lease_seconds=3600,
        )


@activity.defn
async def render_bootstrap_script(intent: DeviceIntent) -> BootstrapScript:
    """
    Render the IOS-XE ZTP Python script from a DeviceIntent.

    Fails fast if default_gateway is missing — the device cannot bootstrap
    without a default route to reach the management network.
    """
    with _tracer.start_as_current_span("render_bootstrap_script") as span:
        span.set_attribute("device.id", intent.device_id)
        log.info(
            "render_bootstrap_script.started",
            device_id=intent.device_id,
            hostname=intent.hostname,
        )

        if not intent.default_gateway:
            raise ValueError(
                f"device_id={intent.device_id} has no default_gateway in Nautobot config context"
            )

        rendered_at = datetime.now(tz=UTC).isoformat()
        template = _JINJA_ENV.from_string(_ZTP_SCRIPT_TEMPLATE)
        script_text = template.render(intent=intent, rendered_at=rendered_at)
        script_url = f"{BOOTSTRAP_SERVER_URL}/ztp/{intent.device_id}.py"

        log.info(
            "render_bootstrap_script.complete",
            device_id=intent.device_id,
            lines=script_text.count("\n"),
            url=script_url,
        )

        return BootstrapScript(
            device_id=intent.device_id,
            script_content=script_text,
            script_url=script_url,
        )


@activity.defn
async def publish_bootstrap_script(script: BootstrapScript) -> None:
    """
    Write the bootstrap script to the HTTP file server directory.

    In production this writes to an nginx-served path or uploads to S3.
    The script must be accessible at script.script_url before the device boots.
    """
    with _tracer.start_as_current_span("publish_bootstrap_script") as span:
        span.set_attribute("device.id", script.device_id)
        script_path = f"{BOOTSTRAP_SERVE_DIR}/{script.device_id}.py"

        log.info(
            "publish_bootstrap_script.started",
            device_id=script.device_id,
            path=script_path,
            url=script.script_url,
        )

        if _USE_MOCK:
            log.debug(
                "publish_bootstrap_script.mock",
                preview="\n".join(script.script_content.splitlines()[:3]),
            )
        else:
            # In production: write to the file server path or upload to object storage.
            with open(script_path, "w") as fh:
                fh.write(script.script_content)

        log.info("publish_bootstrap_script.complete", device_id=script.device_id)


@activity.defn
async def wait_for_device_reachability(device_id: str, management_ip: str) -> bool:
    """
    Poll until the device's management IP accepts SSH connections.

    Uses tenacity for the inner retry loop (30-second poll interval with
    fixed wait).  The outer bound is the Temporal activity start_to_close_timeout
    (8 hours, set in the workflow) — Temporal cancels the activity if that
    expires, which propagates as a failure to the workflow.

    In production: attempts asyncio TCP connect to port 22.  The first
    successful connect means the bootstrap script ran and SSH is up.
    """
    with _tracer.start_as_current_span("wait_for_device_reachability") as span:
        span.set_attribute("device.id", device_id)
        log.info(
            "wait_for_device_reachability.started",
            device_id=device_id,
            management_ip=management_ip,
        )

        if _USE_MOCK:
            log.debug(
                "wait_for_device_reachability.mock",
                poll="SSH port 22 every 30s until reachable",
            )
            await asyncio.sleep(2)
            log.info("wait_for_device_reachability.online", device_id=device_id)
            return True

        # Production: tenacity wraps the SSH probe.
        # stop_after_delay is a safety net — the Temporal 8h timeout is the real bound.
        _ssh_probe_with_retry = retry(
            stop=stop_after_delay(8 * 3600),
            wait=wait_fixed(30),
            reraise=True,
            before_sleep=lambda rs: log.debug(
                "wait_for_device_reachability.retry",
                device_id=device_id,
                attempt=rs.attempt_number,
            ),
        )(_probe_ssh)

        await asyncio.to_thread(_ssh_probe_with_retry, management_ip)
        log.info("wait_for_device_reachability.online", device_id=device_id)
        return True


def _probe_ssh(host: str, port: int = 22, timeout: float = 5.0) -> None:
    """Attempt a TCP connect to host:port.  Raises OSError on failure."""
    import socket

    with socket.create_connection((host, port), timeout=timeout):
        pass
