"""
Day 0 bootstrap activities.

Responsibilities:
  1. register_dhcp_reservation  — pre-create a DHCP reservation for the device's
                                   MAC address so the first DHCP Discover gets the
                                   right IP and Option 67 bootstrap URL.
  2. render_bootstrap_script    — Jinja2-render a Cisco IOS-XE ZTP Python script
                                   from the DeviceIntent.  The script is what the
                                   device actually executes on first boot.
  3. publish_bootstrap_script   — write the rendered script to the HTTP directory
                                   served by the bootstrap file server.
  4. wait_for_device_reachability — poll until the device's management IP responds
                                    to SSH, signalling that the bootstrap script ran
                                    successfully and Day 1 can begin.

Bootstrap flow on the device side (Cisco IOS-XE ZTP):
  1. Device boots with factory defaults, no config.
  2. Sends DHCP Discover on all interfaces.
  3. DHCP server matches the reserved MAC, returns a short-lease IP + Option 67
     pointing at the bootstrap HTTP server URL.
  4. IOS-XE fetches the Python script from the URL.
  5. IOS-XE executes the script using its built-in ``cli`` module.
  6. Script applies minimal config: hostname, mgmt IP, default route, SSH.
  7. Device saves config and becomes reachable — triggers Day 1.
"""

from __future__ import annotations

import asyncio
import logging
import os
import textwrap
from datetime import UTC, datetime

from jinja2 import BaseLoader, Environment, StrictUndefined
from temporalio import activity

from temporal.models import BootstrapScript, DeviceIntent, DhcpReservation

logger = logging.getLogger(__name__)

BOOTSTRAP_SERVER_URL = os.getenv("BOOTSTRAP_SERVER_URL", "http://bootstrap.corp.example.com")
BOOTSTRAP_SERVE_DIR = os.getenv("BOOTSTRAP_SERVE_DIR", "/opt/bootstrap/scripts")
DHCP_API_URL = os.getenv("DHCP_API_URL", "http://localhost:8081")

# ---------------------------------------------------------------------------
# IOS-XE ZTP Python script template
#
# This is the actual script format Cisco IOS-XE executes on first boot via
# its built-in Python 3 interpreter and ``cli`` module.  It applies only the
# configuration needed to bring the management plane up — full Day 1 intent
# is delivered separately by Ansible once the device is reachable.
#
# Key constraints:
#   - Only the ``cli`` module is available (no pip, no stdlib networking).
#   - ``cli.configure()`` accepts a list of IOS config lines.
#   - ``cli.execute()`` runs exec-mode commands.
#   - The script runs as a privileged process; no authentication needed.
# ---------------------------------------------------------------------------
_ZTP_SCRIPT_TEMPLATE = textwrap.dedent("""\
    #!/usr/bin/env python3
    \"\"\"
    IOS-XE ZTP bootstrap script for {{ intent.hostname }}.
    Auto-generated by network-ztp — do not edit manually.
    Rendered: {{ rendered_at }}
    \"\"\"
    import cli
    import time

    HOSTNAME = "{{ intent.hostname }}"
    MGMT_IFACE = "{{ intent.mgmt_interface }}"
    MGMT_IP = "{{ intent.primary_ip | ip_to_ios }}"
    DEFAULT_GW = "{{ intent.default_gateway }}"
    DOMAIN_NAME = "corp.example.com"

    def configure_management() -> None:
        \"\"\"Apply minimal management-plane configuration.\"\"\"
        cli.configure([
            f"hostname {HOSTNAME}",
            f"interface {MGMT_IFACE}",
            f" description ZTP-MGMT",
            f" ip address {MGMT_IP}",
            f" no shutdown",
            f"ip route 0.0.0.0 0.0.0.0 {DEFAULT_GW}",
            f"ip domain-name {DOMAIN_NAME}",
        ])

    def configure_ssh() -> None:
        \"\"\"Enable SSH access for Day 1 Ansible connection.\"\"\"
        # Generate RSA key — required before ssh can be enabled.
        cli.execute("crypto key generate rsa modulus 2048")
        time.sleep(2)  # Key generation is synchronous but takes a moment
        cli.configure([
            "ip ssh version 2",
            "ip ssh time-out 60",
            "ip ssh authentication-retries 3",
            "aaa new-model",
            "aaa authentication login default local",
            "aaa authorization exec default local",
            "line vty 0 15",
            " login authentication default",
            " transport input ssh",
        ])

    def save_config() -> None:
        cli.execute("write memory")

    # Entry point — IOS-XE calls the module at import time.
    configure_management()
    configure_ssh()
    save_config()
    print(f"ZTP bootstrap complete for {HOSTNAME}")
""")

_JINJA_ENV = Environment(loader=BaseLoader(), undefined=StrictUndefined, keep_trailing_newline=True)


def _ip_to_ios(cidr: str) -> str:
    """Convert '10.1.1.1/30' to '10.1.1.1 255.255.255.252' for IOS syntax."""
    if not cidr or "/" not in cidr:
        return cidr
    host, prefix = cidr.split("/")
    bits = int(prefix)
    mask_int = (0xFFFFFFFF << (32 - bits)) & 0xFFFFFFFF
    mask = ".".join(str((mask_int >> shift) & 0xFF) for shift in (24, 16, 8, 0))
    return f"{host} {mask}"


_JINJA_ENV.filters["ip_to_ios"] = _ip_to_ios


@activity.defn
async def register_dhcp_reservation(
    mac_address: str, device_id: str, hostname: str
) -> DhcpReservation:
    """
    Pre-create a DHCP reservation so the device's first Discover gets the
    right management IP and the Option 67 bootstrap script URL.

    In production this calls the DHCP server's management API (ISC DHCP /
    Kea / Infoblox) to create a host reservation keyed on the MAC address.
    The reservation includes:
      - ``fixed-address``: the management IP from Nautobot
      - ``option bootfile-name`` (67): URL of the per-device ZTP script
      - A short lease time (1 hour) — enough for bootstrap, prevents long-term
        squatting on the management IP pool before Day 1 assigns the final address.

    Args:
        mac_address: Factory MAC of the device's management port.
        device_id:   Nautobot device UUID.
        hostname:    Device hostname (used to construct the script URL).

    Returns:
        DhcpReservation record confirming what was registered.
    """
    script_url = f"{BOOTSTRAP_SERVER_URL}/ztp/{device_id}.py"

    dhcp_payload = {
        "mac": mac_address,
        "hostname": hostname,
        "option67": script_url,
        "lease_time": 3600,
    }

    activity.logger.info(
        "[MOCK] Registering DHCP reservation: mac=%s device_id=%s url=%s",
        mac_address,
        device_id,
        script_url,
    )
    activity.logger.info(
        "[MOCK] Would POST %s/api/reservations with payload: %s",
        DHCP_API_URL,
        dhcp_payload,
    )

    # Derive the assigned IP from the Nautobot primary_ip (available in
    # DeviceIntent; passed here as separate args to keep the activity signature
    # simple and independently retryable).
    return DhcpReservation(
        device_id=device_id,
        mac_address=mac_address,
        assigned_ip="10.100.255.1",  # In production: resolved from Nautobot
        lease_seconds=3600,
    )


@activity.defn
async def render_bootstrap_script(intent: DeviceIntent) -> BootstrapScript:
    """
    Render the IOS-XE ZTP Python script from a DeviceIntent.

    The rendered script contains only the management-plane configuration.
    It is intentionally minimal — full intent delivery is Day 1's job.

    Args:
        intent: Device desired state from Nautobot.

    Returns:
        BootstrapScript with the rendered Python script text and its URL.
    """
    activity.logger.info(
        "Rendering ZTP bootstrap script: device_id=%s hostname=%s",
        intent.device_id,
        intent.hostname,
    )

    if not intent.default_gateway:
        raise ValueError(
            f"device_id={intent.device_id} has no default_gateway in Nautobot config context — "
            "required for bootstrap script"
        )

    template = _JINJA_ENV.from_string(_ZTP_SCRIPT_TEMPLATE)
    script_text = template.render(
        intent=intent,
        rendered_at=datetime.now(tz=UTC).isoformat(),
    )

    script_url = f"{BOOTSTRAP_SERVER_URL}/ztp/{intent.device_id}.py"

    activity.logger.info(
        "Bootstrap script rendered: device_id=%s lines=%d url=%s",
        intent.device_id,
        script_text.count("\n"),
        script_url,
    )

    return BootstrapScript(
        device_id=intent.device_id,
        script_content=script_text,
        script_url=script_url,
    )


@activity.defn
async def publish_bootstrap_script(script: BootstrapScript) -> None:
    """
    Write the bootstrap script to the HTTP file server directory.

    In production this writes to a path served by nginx/Apache, or uploads
    to an S3 bucket with a pre-signed URL.  The script must be accessible at
    ``script.script_url`` before the device boots and sends its DHCP Discover.

    Args:
        script: Rendered bootstrap script to publish.
    """
    script_path = f"{BOOTSTRAP_SERVE_DIR}/{script.device_id}.py"

    activity.logger.info(
        "[MOCK] Publishing bootstrap script: device_id=%s path=%s url=%s",
        script.device_id,
        script_path,
        script.script_url,
    )
    activity.logger.info(
        "[MOCK] Script content preview (first 3 lines):\n%s",
        "\n".join(script.script_content.splitlines()[:3]),
    )
    # In production: write script.script_content to script_path on the file server


@activity.defn
async def wait_for_device_reachability(device_id: str, management_ip: str) -> bool:
    """
    Poll until the device's management IP accepts SSH connections.

    This activity has a deliberately long start_to_close_timeout (set in the
    workflow) because it may wait hours for a field engineer to physically rack
    and cable the device.  The polling interval is short so the workflow
    proceeds quickly once the device does check in.

    In production this would attempt a paramiko/asyncssh TCP connect to port 22
    on ``management_ip`` and return True on first success.

    Args:
        device_id:      Nautobot device UUID (for logging).
        management_ip:  IP address (without prefix length) to poll.

    Returns:
        True when the device is reachable.
    """
    activity.logger.info(
        "Waiting for device reachability: device_id=%s management_ip=%s",
        device_id,
        management_ip,
    )
    activity.logger.info(
        "[MOCK] Would poll SSH port 22 at %s every 30s until reachable",
        management_ip,
    )

    # Simulate the bootstrap script running and the device coming up.
    await asyncio.sleep(2)

    activity.logger.info(
        "Device is reachable: device_id=%s management_ip=%s",
        device_id,
        management_ip,
    )
    return True
